### ISSUE TITLE
Creazione logica "find" per il cerca 

### ISSUE THREAD

**Issue by Matteosalvatori4** [Matteosalvatori4/rubrica-telefonica-gruppo2#7]
Creazione logica "find" per il cerca sia lato client che lato server

**Comment by Ioana21-b** [comment]
Implementato lato server con Commit 0f0e43d15128fd7352a8654c76f663370fd9adee

**Comment by Fmarro** [comment]
completata verifica funzionamento logica find, e implementazione logica cancella contatto da schermata search con commit daa868503b3ed98cf5a012c2d7c9ad559deb0d6e
