### ISSUE TITLE
Implementazione grafiche interfacce 

### ISSUE THREAD

**Issue by Fmarro** [Matteosalvatori4/rubrica-telefonica-gruppo2#9]
implementazione delle varie schermate attraverso i css

**Comment by lollo996** [comment]
implementazione interfaccia grafica senza utilizzo del server 13dff604d0073bfcafb53bfd3df66eb3ddc5af57.
Da testare con Server attivo

**Comment by Matteosalvatori4** [comment]
Testato e funzionante
